# docker-compose.yml
version: "3.9"

services:
  broker:
    build: ./broker
    ports:
      - "8000:8000"
    volumes:
      - ./broker:/app
    command: uvicorn broker:app --host 0.0.0.0 --port 8000 --reload
